### ISSUE TITLE
release 1.2.0 breaks puppet librarian

### ISSUE THREAD

**Issue by meatherly** [boxen/puppet-qt#8]
When I add 

``` ruby
github "qt", "1.2.0"
```

To my puppet file I get this error

``` sh
[Librarian]   [:github_tarball, "boxen/puppet-qt", {}]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1563:in `path': no implicit conversion of nil into String (TypeError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1563:in `fu_each_src_dest0'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1549:in `fu_each_src_dest'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-0.9.15/lib/librarian/puppet/util.rb:21:in `cp_r'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-0.9.15/lib/librarian/puppet/source/githubtarball.rb:62:in `install_version!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-0.9.15/lib/librarian/puppet/source/githubtarball.rb:234:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:165:in `install!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-0.9.15/lib/librarian/puppet/cli.rb:71:in `install'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
    from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/librarian-puppet-0.9.15/bin/librarian-puppet:7:in `<top (required)>'
    from /opt/boxen/repo/bin/librarian-puppet:16:in `load'
    from /opt/boxen/repo/bin/librarian-puppet:16:in `<main>'
Can't run Puppet, fetching dependencies with librarian failed.
```

Is there something I'm doing wrong?

**Comment by meatherly** [comment]
I think it might be something to do with the brew package I tried adding this to my manifest 

``` puppet
    package { "qt":
      ensure => present,
    }
```

And then I get this error:

``` sh
Debug: Executing 'brew install qt --build-from-source'
Error: Execution of 'brew install qt --build-from-source' returned 1: ==> Downloading https://github.com/qtproject/qt/archive/f44310c25b372f494586dbb5b305f7e81ca63000.tar.gz
Error: Failed to download resource "qt"
Download failed: https://github.com/qtproject/qt/archive/f44310c25b372f494586dbb5b305f7e81ca63000.tar.gz

Error: /Stage[main]/Projects::Metova_dev_setup::Ruby_tools/Package[qt]/ensure: change from absent to present failed: Execution of 'brew install qt --build-from-source' returned 1: ==> Downloading https://github.com/qtproject/qt/archive/f44310c25b372f494586dbb5b305f7e81ca63000.tar.gz
Error: Failed to download resource "qt"
Download failed: https://github.com/qtproject/qt/archive/f44310c25b372f494586dbb5b305f7e81ca63000.tar.gz
```

**Comment by meatherly** [comment]
Anyone have this problem yet?

**Comment by jacobbednarz** [comment]
Closing due to inactivity. Please mention me if this is still an issue.
